DEBUG 2022-03-01 17:12:28.828 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-03-01 17:12:28.829 UTC: 	 Running on: Linux lxplus7101.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-03-01 17:12:28.829 UTC: 	 Executing command: 'submit'
DEBUG 2022-03-01 17:12:28.829 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/ballmond/.crab3
INFO 2022-03-01 17:12:28.830 UTC: 	 Will use CRAB configuration file crabNoPy.py
DEBUG 2022-03-01 17:12:28.830 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-03-01 17:12:28.831 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-03-01 17:12:28.831 UTC: 	 Working area '/afs/cern.ch/user/b/ballmond/public/CMSSW_12_3_0_pre5/src/VBFIsoTauHLT/python/crab/test/crab_VBF_SteamConfTest' already exists 
Please change the requestName in the config file
ERROR 2022-03-01 17:12:28.831 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/user/b/ballmond/public/CMSSW_12_3_0_pre5/src/VBFIsoTauHLT/python/crab/test/crab_VBF_SteamConfTest' already exists 
Please change the requestName in the config file
INFO 2022-03-01 17:12:28.835 UTC: 	 Log file is /afs/cern.ch/user/b/ballmond/public/CMSSW_12_3_0_pre5/src/VBFIsoTauHLT/python/crab/crab.log
DEBUG 2022-03-03 17:52:41.532 UTC: 	 CRAB Client version: v3.220210
DEBUG 2022-03-03 17:52:41.532 UTC: 	 Running on: Linux lxplus719.cern.ch 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-03-03 17:52:41.532 UTC: 	 Executing command: 'submit'
DEBUG 2022-03-03 17:52:41.533 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/ballmond/.crab3
INFO 2022-03-03 17:52:41.534 UTC: 	 Will use CRAB configuration file crabNoPy.py
DEBUG 2022-03-03 17:52:41.534 UTC: 	 Loading CRAB configuration file.
DEBUG 2022-03-03 17:52:41.538 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2022-03-03 17:52:41.542 UTC: 	 Working area '/afs/cern.ch/user/b/ballmond/public/CMSSW_12_3_0_pre5/src/VBFIsoTauHLT/NtupleMaker/python/crab/test/crab_VBF_Pre5Eff' already exists 
Please change the requestName in the config file
ERROR 2022-03-03 17:52:41.542 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 162, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/bin/crab.py", line 147, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220210.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/afs/cern.ch/user/b/ballmond/public/CMSSW_12_3_0_pre5/src/VBFIsoTauHLT/NtupleMaker/python/crab/test/crab_VBF_Pre5Eff' already exists 
Please change the requestName in the config file
INFO 2022-03-03 17:52:41.562 UTC: 	 Log file is /afs/cern.ch/user/b/ballmond/public/CMSSW_12_3_0_pre5/src/VBFIsoTauHLT/NtupleMaker/python/crab/crab.log
